### PR TITLE
[feat] support more system types and use flake.parts

### PR DESCRIPTION
**Pull request by MangoIV**
I don't have a mac myself so no idea if it works; I can try to build on aarch64-linux though.

### CODE REVIEW

**Comment by MangoIV** [comment]
everything builds on aarch64-linux

**Comment by MangoIV** [comment]
image

i also took the freedom to make it a bit cute

**Comment by semickolon** [comment]
LGTM so far! TIL that `mkShell` is not as "clean" as I thought.

Just one thing. Why are we adding `gcc`?

**Comment by MangoIV** [comment]
Because mkShell normally adds a C compiler, that’s why you should normally use mkShellNoCC if you don’t want one. I couldn’t make it work without gcc added to the shell so I was assuming you were implicitly relying on that.

**Comment by semickolon** [comment]
`meson` apparently does sanity checks and wants a C compiler in the env. I looked for how to disable this check but there doesn't seem to be a sensible non-hacky way to do it. We'll leave `gcc` there for now.

Thank you! :partying_face:

**Pull request merged**
